import { School } from '../types/school';
import { Incident } from '../types/incident';
import { EarlyWarning, ActivityEvent, NotificationItem, NetworkHealthSummary } from '../types/health';

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'SCH-001',
    name: 'Школа-гимназия №38 им. Льва Гуляева',
    district: 'г. Усть-Каменогорск',
    city: 'Усть-Каменогорск',
    latitude: 49.9575,
    longitude: 82.6050,
    status: 'healthy',
    healthScore: 95,
    lastMeasurement: {
      id: 'm-001',
      schoolId: 'SCH-001',
      deviceId: 'DEV-UK-01',
      timestamp: new Date().toISOString(),
      pingMs: 22,
      jitterMs: 4,
      packetLossPercent: 0.0,
      downloadMbps: 96.4,
      uploadMbps: 48.6,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-UK-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.142.12.10',
    isp: 'АО «Казахтелеком» (GPON)',
    connectionType: 'Fiber',
    studentCount: 860,
    trend: 'improving',
    recentPingHistory: [26, 25, 24, 23, 22],
    recentDownloadHistory: [92.0, 93.5, 95.0, 96.0, 96.4],
  },
  {
    id: 'SCH-002',
    name: 'IT-лицей №1 для одарённых детей',
    district: 'г. Усть-Каменогорск',
    city: 'Усть-Каменогорск',
    latitude: 49.9720,
    longitude: 82.6280,
    status: 'healthy',
    healthScore: 98,
    lastMeasurement: {
      id: 'm-002',
      schoolId: 'SCH-002',
      deviceId: 'DEV-UK-02',
      timestamp: new Date().toISOString(),
      pingMs: 15,
      jitterMs: 2,
      packetLossPercent: 0.0,
      downloadMbps: 185.0,
      uploadMbps: 95.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-UK-02',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.142.12.18',
    isp: 'АО «Транстелеком» (Metro Ethernet)',
    connectionType: 'Fiber',
    studentCount: 640,
    trend: 'stable',
    recentPingHistory: [16, 15, 16, 15, 15],
    recentDownloadHistory: [180, 182, 184, 185, 185],
  },
  {
    id: 'SCH-003',
    name: 'Средняя профильная школа №25',
    district: 'г. Усть-Каменогорск',
    city: 'Усть-Каменогорск',
    latitude: 49.9450,
    longitude: 82.5920,
    status: 'warning',
    healthScore: 71,
    lastMeasurement: {
      id: 'm-003',
      schoolId: 'SCH-003',
      deviceId: 'DEV-UK-03',
      timestamp: new Date().toISOString(),
      pingMs: 118,
      jitterMs: 38,
      packetLossPercent: 3.4,
      downloadMbps: 18.4,
      uploadMbps: 6.2,
    },
    agentStatus: 'online',
    lastHeartbeat: '30 сек назад',
    deviceId: 'DEV-UK-03',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.142.14.45',
    isp: 'АО «Казахтелеком» (FTTB)',
    connectionType: 'Fiber',
    studentCount: 1120,
    trend: 'degrading',
    recentPingHistory: [52, 68, 85, 102, 118],
    recentDownloadHistory: [45.0, 38.0, 29.5, 22.0, 18.4],
    mainIssue: 'Рост джиттера и перегрузка буфера коммутатора',
  },
  {
    id: 'SCH-004',
    name: 'Средняя школа №12 им. М. Горького',
    district: 'г. Усть-Каменогорск',
    city: 'Усть-Каменогорск',
    latitude: 49.9810,
    longitude: 82.5650,
    status: 'healthy',
    healthScore: 89,
    lastMeasurement: {
      id: 'm-004',
      schoolId: 'SCH-004',
      deviceId: 'DEV-UK-04',
      timestamp: new Date().toISOString(),
      pingMs: 32,
      jitterMs: 5,
      packetLossPercent: 0.1,
      downloadMbps: 64.0,
      uploadMbps: 28.5,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-UK-04',
    agentVersion: 'v2.4.0-net8',
    ipAddress: '10.142.15.22',
    isp: 'Beeline Business Оптика',
    connectionType: 'Fiber',
    studentCount: 750,
    trend: 'stable',
    recentPingHistory: [31, 33, 30, 32, 32],
    recentDownloadHistory: [63, 64, 62, 65, 64],
  },
  {
    id: 'SCH-005',
    name: 'Средняя школа №14 им. А. Чехова',
    district: 'г. Усть-Каменогорск',
    city: 'Усть-Каменогорск',
    latitude: 49.9630,
    longitude: 82.6390,
    status: 'healthy',
    healthScore: 92,
    lastMeasurement: {
      id: 'm-005b',
      schoolId: 'SCH-005',
      deviceId: 'DEV-UK-05',
      timestamp: new Date().toISOString(),
      pingMs: 26,
      jitterMs: 4,
      packetLossPercent: 0.1,
      downloadMbps: 88.0,
      uploadMbps: 40.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-UK-05',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.142.16.11',
    isp: 'АО «Казахтелеком» (GPON)',
    connectionType: 'Fiber',
    studentCount: 890,
    trend: 'stable',
    recentPingHistory: [25, 27, 26, 25, 26],
    recentDownloadHistory: [86, 88, 87, 89, 88],
  },
  {
    id: 'SCH-006',
    name: 'Многопрофильный лицей №1',
    district: 'г. Риддер',
    city: 'Риддер',
    latitude: 50.3450,
    longitude: 83.5120,
    status: 'healthy',
    healthScore: 93,
    lastMeasurement: {
      id: 'm-006',
      schoolId: 'SCH-006',
      deviceId: 'DEV-RD-01',
      timestamp: new Date().toISOString(),
      pingMs: 29,
      jitterMs: 4,
      packetLossPercent: 0.0,
      downloadMbps: 95.0,
      uploadMbps: 42.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-RD-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.144.10.8',
    isp: 'АО «Казахтелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 610,
    trend: 'stable',
    recentPingHistory: [29, 30, 28, 29, 29],
    recentDownloadHistory: [94, 95, 93, 96, 95],
  },
  {
    id: 'SCH-007',
    name: 'Горно-экологическая гимназия №3',
    district: 'г. Риддер',
    city: 'Риддер',
    latitude: 50.3580,
    longitude: 83.5350,
    status: 'warning',
    healthScore: 68,
    lastMeasurement: {
      id: 'm-007',
      schoolId: 'SCH-007',
      deviceId: 'DEV-RD-02',
      timestamp: new Date().toISOString(),
      pingMs: 134,
      jitterMs: 42,
      packetLossPercent: 4.8,
      downloadMbps: 12.6,
      uploadMbps: 4.5,
    },
    agentStatus: 'online',
    lastHeartbeat: '1 мин назад',
    deviceId: 'DEV-RD-02',
    agentVersion: 'v2.4.0-net8',
    ipAddress: '10.144.12.19',
    isp: 'АО «Казахтелеком» (Медная линия VDSL)',
    connectionType: 'DSL',
    studentCount: 490,
    trend: 'degrading',
    recentPingHistory: [64, 82, 99, 118, 134],
    recentDownloadHistory: [32.0, 24.0, 18.5, 14.2, 12.6],
    mainIssue: 'Шумы в медной распределительной линии',
  },
  {
    id: 'SCH-008',
    name: 'Средняя общеобразовательная школа №8',
    district: 'район Алтай',
    city: 'Алтай',
    latitude: 49.7340,
    longitude: 84.2680,
    status: 'healthy',
    healthScore: 88,
    lastMeasurement: {
      id: 'm-008',
      schoolId: 'SCH-008',
      deviceId: 'DEV-AL-01',
      timestamp: new Date().toISOString(),
      pingMs: 44,
      jitterMs: 7,
      packetLossPercent: 0.2,
      downloadMbps: 72.0,
      uploadMbps: 30.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-AL-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.145.10.15',
    isp: 'АО «Транстелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 520,
    trend: 'stable',
    recentPingHistory: [42, 45, 43, 46, 44],
    recentDownloadHistory: [70, 71, 72, 73, 72],
  },
  {
    id: 'SCH-009',
    name: 'Средняя школа №2 им. Абая',
    district: 'район Алтай',
    city: 'Алтай',
    latitude: 49.7210,
    longitude: 84.2490,
    status: 'healthy',
    healthScore: 86,
    lastMeasurement: {
      id: 'm-009',
      schoolId: 'SCH-009',
      deviceId: 'DEV-AL-02',
      timestamp: new Date().toISOString(),
      pingMs: 48,
      jitterMs: 8,
      packetLossPercent: 0.3,
      downloadMbps: 66.0,
      uploadMbps: 28.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-AL-02',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.145.11.20',
    isp: 'АО «Казахтелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 470,
    trend: 'stable',
    recentPingHistory: [49, 47, 48, 48, 48],
    recentDownloadHistory: [65, 66, 67, 66, 66],
  },
  {
    id: 'SCH-010',
    name: 'Средняя школа №2',
    district: 'район Алтай',
    city: 'Серебрянск',
    latitude: 49.6800,
    longitude: 83.3000,
    status: 'healthy',
    healthScore: 87,
    lastMeasurement: {
      id: 'm-010',
      schoolId: 'SCH-010',
      deviceId: 'DEV-SB-01',
      timestamp: new Date().toISOString(),
      pingMs: 38,
      jitterMs: 7,
      packetLossPercent: 0.2,
      downloadMbps: 65.0,
      uploadMbps: 26.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-SB-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.153.10.7',
    isp: 'АО «Казахтелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 410,
    trend: 'stable',
    recentPingHistory: [39, 38, 37, 39, 38],
    recentDownloadHistory: [64, 65, 66, 64, 65],
  },
  {
    id: 'SCH-011',
    name: 'Школа-лицей №2 им. Н. Островского',
    district: 'Шемонаихинский район',
    city: 'Шемонаиха',
    latitude: 50.6270,
    longitude: 81.9120,
    status: 'healthy',
    healthScore: 86,
    lastMeasurement: {
      id: 'm-011',
      schoolId: 'SCH-011',
      deviceId: 'DEV-SH-01',
      timestamp: new Date().toISOString(),
      pingMs: 48,
      jitterMs: 9,
      packetLossPercent: 0.3,
      downloadMbps: 68.0,
      uploadMbps: 25.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-SH-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.146.10.4',
    isp: 'АО «Казахтелеком» (FTTH)',
    connectionType: 'Fiber',
    studentCount: 680,
    trend: 'improving',
    recentPingHistory: [54, 52, 50, 49, 48],
    recentDownloadHistory: [60, 62, 65, 67, 68],
  },
  {
    id: 'SCH-012',
    name: 'Курчумская средняя школа №1 им. Ю. Гагарина',
    district: 'Курчумский район',
    city: 'Курчум',
    latitude: 48.5600,
    longitude: 83.6500,
    status: 'healthy',
    healthScore: 84,
    lastMeasurement: {
      id: 'm-012',
      schoolId: 'SCH-012',
      deviceId: 'DEV-KR-01',
      timestamp: new Date().toISOString(),
      pingMs: 58,
      jitterMs: 12,
      packetLossPercent: 0.6,
      downloadMbps: 52.0,
      uploadMbps: 22.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-KR-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.158.10.3',
    isp: 'АО «Казахтелеком» (Радиомагистраль)',
    connectionType: 'Wireless / Radio',
    studentCount: 420,
    trend: 'stable',
    recentPingHistory: [57, 59, 60, 58, 58],
    recentDownloadHistory: [50, 51, 52, 53, 52],
  },
  {
    id: 'SCH-013',
    name: 'Средняя школа №1 им. Ы. Алтынсарина',
    district: 'Глубоковский район',
    city: 'Глубокое',
    latitude: 50.1410,
    longitude: 82.3110,
    status: 'healthy',
    healthScore: 91,
    lastMeasurement: {
      id: 'm-013',
      schoolId: 'SCH-013',
      deviceId: 'DEV-GL-01',
      timestamp: new Date().toISOString(),
      pingMs: 27,
      jitterMs: 5,
      packetLossPercent: 0.1,
      downloadMbps: 90.0,
      uploadMbps: 42.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-GL-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.151.10.6',
    isp: 'АО «Казахтелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 570,
    trend: 'stable',
    recentPingHistory: [28, 27, 26, 28, 27],
    recentDownloadHistory: [88, 90, 89, 91, 90],
  },
  {
    id: 'SCH-014',
    name: 'Катон-Карагайская сельская школа им. С. Рыкова',
    district: 'Катон-Карагайский район',
    city: 'Катон-Карагай',
    latitude: 49.1760,
    longitude: 85.6020,
    status: 'warning',
    healthScore: 64,
    lastMeasurement: {
      id: 'm-014',
      schoolId: 'SCH-014',
      deviceId: 'DEV-KK-01',
      timestamp: new Date().toISOString(),
      pingMs: 121,
      jitterMs: 28,
      packetLossPercent: 2.1,
      downloadMbps: 8.4,
      uploadMbps: 2.3,
    },
    agentStatus: 'online',
    lastHeartbeat: '2 мин назад',
    deviceId: 'DEV-KK-01',
    agentVersion: 'v2.4.0-net8',
    ipAddress: '10.150.10.8',
    isp: 'KazTransCom Радиоканал / VSAT Backup',
    connectionType: 'Wireless / Radio',
    studentCount: 220,
    trend: 'degrading',
    recentPingHistory: [72, 84, 96, 109, 121],
    recentDownloadHistory: [18.0, 15.2, 12.0, 9.8, 8.4],
    mainIssue: 'Раннее предупреждение: последовательный рост задержки (72 → 121 мс)',
  },
  {
    id: 'SCH-015',
    name: 'Самарская средняя общеобразовательная школа №1',
    district: 'Кокпектинский / Самарский район',
    city: 'Самарское',
    latitude: 49.0300,
    longitude: 83.3300,
    status: 'healthy',
    healthScore: 79,
    lastMeasurement: {
      id: 'm-015',
      schoolId: 'SCH-015',
      deviceId: 'DEV-SM-03',
      timestamp: new Date().toISOString(),
      pingMs: 68,
      jitterMs: 16,
      packetLossPercent: 1.1,
      downloadMbps: 36.0,
      uploadMbps: 14.0,
    },
    agentStatus: 'online',
    lastHeartbeat: '3 мин назад',
    deviceId: 'DEV-SM-03',
    agentVersion: 'v2.4.0-net8',
    ipAddress: '10.155.10.14',
    isp: 'АО «Транстелеком» Радиоканал',
    connectionType: 'Wireless / Radio',
    studentCount: 280,
    trend: 'stable',
    recentPingHistory: [67, 69, 70, 68, 68],
    recentDownloadHistory: [35, 36, 37, 35, 36],
  },
  {
    id: 'SCH-016',
    name: 'Средняя школа №1 им. Абая',
    district: 'Зайсанский район',
    city: 'Зайсан',
    latitude: 47.4720,
    longitude: 84.8710,
    status: 'healthy',
    healthScore: 82,
    lastMeasurement: {
      id: 'm-016',
      schoolId: 'SCH-016',
      deviceId: 'DEV-ZS-01',
      timestamp: new Date().toISOString(),
      pingMs: 62,
      jitterMs: 14,
      packetLossPercent: 0.8,
      downloadMbps: 45.0,
      uploadMbps: 18.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-ZS-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.149.10.11',
    isp: 'АО «Казахтелеком» Радиорелейный тракт',
    connectionType: 'Wireless / Radio',
    studentCount: 440,
    trend: 'stable',
    recentPingHistory: [60, 64, 61, 63, 62],
    recentDownloadHistory: [44, 46, 45, 43, 45],
  },
  {
    id: 'SCH-017',
    name: 'Средняя школа посёлка Жезкент',
    district: 'Бородулихинский район',
    city: 'Жезкент',
    latitude: 50.9160,
    longitude: 81.3830,
    status: 'critical',
    healthScore: 42,
    lastMeasurement: {
      id: 'm-017',
      schoolId: 'SCH-017',
      deviceId: 'DEV-BR-01',
      timestamp: new Date().toISOString(),
      pingMs: 248,
      jitterMs: 76,
      packetLossPercent: 12.8,
      downloadMbps: 3.4,
      uploadMbps: 1.1,
    },
    agentStatus: 'online',
    lastHeartbeat: '45 сек назад',
    deviceId: 'DEV-BR-01',
    agentVersion: 'v2.4.0-net8',
    ipAddress: '10.148.21.14',
    isp: 'KazTransCom Радиорелейная линия',
    connectionType: 'Wireless / Radio',
    studentCount: 380,
    trend: 'degrading',
    recentPingHistory: [140, 175, 210, 230, 248],
    recentDownloadHistory: [12.0, 9.5, 6.2, 4.0, 3.4],
    mainIssue: 'Критическая потеря пакетов 12.8% и задержка 248 мс',
  },
  {
    id: 'SCH-018',
    name: 'Аксуатская средняя школа №1',
    district: 'Тарбагатайский / Аксуатский район',
    city: 'Аксуат',
    latitude: 47.7810,
    longitude: 82.7840,
    status: 'critical',
    healthScore: 38,
    lastMeasurement: {
      id: 'm-018',
      schoolId: 'SCH-018',
      deviceId: 'DEV-AK-01',
      timestamp: new Date().toISOString(),
      pingMs: 295,
      jitterMs: 84,
      packetLossPercent: 18.5,
      downloadMbps: 1.8,
      uploadMbps: 0.6,
    },
    agentStatus: 'online',
    lastHeartbeat: '1 мин назад',
    deviceId: 'DEV-AK-01',
    agentVersion: 'v2.3.9-net8',
    ipAddress: '10.152.12.3',
    isp: 'Сельская радиолиния',
    connectionType: 'Wireless / Radio',
    studentCount: 290,
    trend: 'degrading',
    recentPingHistory: [160, 195, 230, 270, 295],
    recentDownloadHistory: [6.0, 4.2, 3.0, 2.1, 1.8],
    mainIssue: 'Потери 18.5% и просадка канала ниже 2 Мбит/с',
  },
  {
    id: 'SCH-019',
    name: 'Средняя общеобразовательная школа №4',
    district: 'Аягозский район',
    city: 'Аягоз',
    latitude: 47.9620,
    longitude: 80.4350,
    status: 'healthy',
    healthScore: 84,
    lastMeasurement: {
      id: 'm-019',
      schoolId: 'SCH-019',
      deviceId: 'DEV-AY-01',
      timestamp: new Date().toISOString(),
      pingMs: 56,
      jitterMs: 11,
      packetLossPercent: 0.4,
      downloadMbps: 54.0,
      uploadMbps: 22.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-AY-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.154.10.12',
    isp: 'АО «Казахтелеком» (GPON)',
    connectionType: 'Fiber',
    studentCount: 510,
    trend: 'improving',
    recentPingHistory: [62, 59, 58, 57, 56],
    recentDownloadHistory: [48, 50, 52, 53, 54],
  },
  {
    id: 'SCH-020',
    name: 'Урджарская гимназия №1 им. Абая',
    district: 'Урджарский район',
    city: 'Урджар',
    latitude: 47.0930,
    longitude: 81.6290,
    status: 'healthy',
    healthScore: 85,
    lastMeasurement: {
      id: 'm-020',
      schoolId: 'SCH-020',
      deviceId: 'DEV-UR-01',
      timestamp: new Date().toISOString(),
      pingMs: 51,
      jitterMs: 8,
      packetLossPercent: 0.3,
      downloadMbps: 62.0,
      uploadMbps: 27.0,
    },
    agentStatus: 'offline',
    lastHeartbeat: '14 минут назад',
    deviceId: 'DEV-UR-01',
    agentVersion: 'v2.4.0-net8',
    ipAddress: '10.156.10.9',
    isp: 'АО «Казахтелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 460,
    trend: 'stable',
    recentPingHistory: [52, 50, 51, 52, 51],
    recentDownloadHistory: [60, 61, 62, 62, 62],
    mainIssue: 'Агент офлайн (нет heartbeat более 10 минут)',
  },
  {
    id: 'SCH-021',
    name: 'Школа-интернат им. И. Курчатова',
    district: 'г. Курчатов',
    city: 'Курчатов',
    latitude: 50.7580,
    longitude: 78.5380,
    status: 'healthy',
    healthScore: 93,
    lastMeasurement: {
      id: 'm-021',
      schoolId: 'SCH-021',
      deviceId: 'DEV-KC-01',
      timestamp: new Date().toISOString(),
      pingMs: 27,
      jitterMs: 4,
      packetLossPercent: 0.0,
      downloadMbps: 110.0,
      uploadMbps: 55.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-KC-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.147.10.2',
    isp: 'АО «Транстелеком» Metro-E',
    connectionType: 'Fiber',
    studentCount: 310,
    trend: 'stable',
    recentPingHistory: [26, 28, 27, 27, 27],
    recentDownloadHistory: [108, 110, 109, 111, 110],
  },
  {
    id: 'SCH-022',
    name: 'Уланская средняя школа им. К. Кайсенова',
    district: 'Уланский район',
    city: 'пос. Касыма Кайсенова',
    latitude: 49.9760,
    longitude: 82.5210,
    status: 'healthy',
    healthScore: 89,
    lastMeasurement: {
      id: 'm-022',
      schoolId: 'SCH-022',
      deviceId: 'DEV-UL-01',
      timestamp: new Date().toISOString(),
      pingMs: 31,
      jitterMs: 5,
      packetLossPercent: 0.1,
      downloadMbps: 78.0,
      uploadMbps: 35.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-UL-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.157.10.5',
    isp: 'АО «Казахтелеком» (Оптика)',
    connectionType: 'Fiber',
    studentCount: 540,
    trend: 'stable',
    recentPingHistory: [32, 31, 30, 31, 31],
    recentDownloadHistory: [76, 77, 78, 79, 78],
  },
  {
    id: 'SCH-023',
    name: 'Назарбаев Интеллектуальная школа (НИШ)',
    district: 'г. Семей',
    city: 'Семей',
    latitude: 50.4111,
    longitude: 80.2275,
    status: 'healthy',
    healthScore: 97,
    lastMeasurement: {
      id: 'm-023',
      schoolId: 'SCH-023',
      deviceId: 'DEV-SM-01',
      timestamp: new Date().toISOString(),
      pingMs: 18,
      jitterMs: 3,
      packetLossPercent: 0.0,
      downloadMbps: 175.0,
      uploadMbps: 90.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-SM-01',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.143.10.12',
    isp: 'АО «Транстелеком» Metro-E',
    connectionType: 'Fiber',
    studentCount: 720,
    trend: 'stable',
    recentPingHistory: [18, 19, 18, 17, 18],
    recentDownloadHistory: [172, 174, 175, 175, 175],
  },
  {
    id: 'SCH-024',
    name: 'Гимназия №6 им. Ф. Достоевского',
    district: 'г. Семей',
    city: 'Семей',
    latitude: 50.4280,
    longitude: 80.2540,
    status: 'healthy',
    healthScore: 91,
    lastMeasurement: {
      id: 'm-024',
      schoolId: 'SCH-024',
      deviceId: 'DEV-SM-02',
      timestamp: new Date().toISOString(),
      pingMs: 34,
      jitterMs: 6,
      packetLossPercent: 0.1,
      downloadMbps: 84.0,
      uploadMbps: 36.0,
    },
    agentStatus: 'online',
    lastHeartbeat: 'Только что',
    deviceId: 'DEV-SM-02',
    agentVersion: 'v2.4.1-net8',
    ipAddress: '10.143.11.33',
    isp: 'АО «Казахтелеком» (GPON)',
    connectionType: 'Fiber',
    studentCount: 940,
    trend: 'stable',
    recentPingHistory: [35, 34, 33, 35, 34],
    recentDownloadHistory: [82, 83, 84, 85, 84],
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-4091',
    schoolId: 'SCH-017',
    schoolName: 'Средняя школа посёлка Жезкент',
    type: 'Packet loss',
    severity: 'critical',
    status: 'active',
    createdAt: '24 минуты назад',
    value: 'Потери пакетов достигли 12.8%',
    threshold: 'Порог: 10.0%',
    description: 'Критическое выпадение пакетов на радиорелейном сегменте связи между Жезкентом и опорным маршрутизатором района.',
    acknowledged: false,
    duration: '24 мин',
    timeDetected: '14:24:00',
    potentialReason: 'Высокий уровень электромагнитных помех и деградация радиосигнала на антенном посту',
    telemetrySnapshot: {
      pingMs: 248,
      jitterMs: 76,
      packetLossPercent: 12.8,
      downloadMbps: 3.4,
      uploadMbps: 1.1,
    },
    timeline: [
      { timestamp: '14:02:10', stage: 'Норма', note: 'Потери на базовом уровне 0.4%, пинг 45 мс', level: 'normal' },
      { timestamp: '14:11:45', stage: 'Нестабильность', note: 'Потери выросли до 4.5% в период школьных онлайн-занятий', level: 'info' },
      { timestamp: '14:18:20', stage: 'Предупреждение', note: 'Превышен порог 8.0%, рост отброшенных кадров (CRC errors)', level: 'warning' },
      { timestamp: '14:24:00', stage: 'Превышение порога', note: 'Превышен критический порог 10% (12.8%). Автоматически открыт инцидент.', level: 'critical' },
    ],
  },
  {
    id: 'INC-4092',
    schoolId: 'SCH-018',
    schoolName: 'Аксуатская средняя школа №1',
    type: 'High latency',
    severity: 'critical',
    status: 'active',
    createdAt: '18 минут назад',
    value: 'Ping увеличился до 295 мс',
    threshold: 'Порог: 150 мс',
    description: 'Резкий скачок круговой задержки (RTT) и насыщение сетевых буферов на сельском радиоретрансляторе в часы пиковой нагрузки.',
    acknowledged: true,
    acknowledgedAt: '14:30',
    acknowledgedBy: 'Ерболат К. (Дежурный инженер NOC)',
    duration: '18 мин',
    timeDetected: '14:26:00',
    potentialReason: 'Перегрузка полосы пропускания uplink-канала сельской базовой станции',
    telemetrySnapshot: {
      pingMs: 295,
      jitterMs: 84,
      packetLossPercent: 18.5,
      downloadMbps: 1.8,
      uploadMbps: 0.6,
    },
    timeline: [
      { timestamp: '14:05:00', stage: 'Норма', note: 'Задержка в норме: 68 мс', level: 'normal' },
      { timestamp: '14:16:15', stage: 'Задержка растёт', note: 'Пинг плавно поднялся от 95 мс до 160 мс', level: 'warning' },
      { timestamp: '14:26:00', stage: 'Критический порог', note: 'Пинг достиг максимума 295 мс с переполнением аппаратной очереди', level: 'critical' },
    ],
  },
  {
    id: 'INC-4089',
    schoolId: 'SCH-003',
    schoolName: 'Средняя профильная школа №25',
    type: 'High jitter',
    severity: 'warning',
    status: 'active',
    createdAt: '42 минуты назад',
    value: 'Джиттер вырос до 38 мс',
    threshold: 'Порог: 30 мс',
    description: 'Сильные колебания времени доставки пакетов, вызывающие зависание образовательных платформ (Кунделик, BilimLand) и видеоконференций.',
    acknowledged: false,
    duration: '42 мин',
    timeDetected: '13:58:30',
    potentialReason: 'Колебания очередей коммутатора (Bufferbloat) при массовой загрузке учебных материалов',
    telemetrySnapshot: {
      pingMs: 118,
      jitterMs: 38,
      packetLossPercent: 3.4,
      downloadMbps: 18.4,
      uploadMbps: 6.2,
    },
    timeline: [
      { timestamp: '13:45:00', stage: 'Норма', note: 'Джиттер стабилен на уровне 5 мс', level: 'normal' },
      { timestamp: '13:58:30', stage: 'Порог предупреждения', note: 'Дрожание задержки увеличилось до 38 мс', level: 'warning' },
    ],
  },
  {
    id: 'INC-4085',
    schoolId: 'SCH-007',
    schoolName: 'Горно-экологическая гимназия №3',
    type: 'Network degradation',
    severity: 'warning',
    status: 'active',
    createdAt: '1 час назад',
    value: 'Скорость снизилась до 12.6 Мбит/с, Ping 134 мс',
    threshold: 'Порог: Ping >= 150 мс или Download < 15 Мбит/с',
    description: 'Комплексная деградация пропускной способности и времени отклика на медной кабельной линии VDSL.',
    acknowledged: true,
    acknowledgedAt: '13:30',
    acknowledgedBy: 'Дана С. (Региональный оператор ВКО)',
    duration: '1 час 15 мин',
    timeDetected: '13:25:00',
    potentialReason: 'Окисление контактов в абонентском шкафу после перепада влажности',
    telemetrySnapshot: {
      pingMs: 134,
      jitterMs: 42,
      packetLossPercent: 4.8,
      downloadMbps: 12.6,
      uploadMbps: 4.5,
    },
    timeline: [
      { timestamp: '13:10:00', stage: 'Норма', note: 'Скорость 48 Мбит/с, пинг 34 мс', level: 'normal' },
      { timestamp: '13:25:00', stage: 'Деградация', note: 'Скорость упала ниже 15 Мбит/с при флуктуациях SNR', level: 'warning' },
    ],
  },
  {
    id: 'INC-4078',
    schoolId: 'SCH-006',
    schoolName: 'Многопрофильный лицей №1',
    type: 'High latency',
    severity: 'warning',
    status: 'resolved',
    createdAt: '3 часа назад',
    resolvedAt: '1 час назад',
    value: 'Ping поднимался до 168 мс',
    threshold: 'Порог: 150 мс',
    description: 'Временная перемаршрутизация оптоволоконного трафика из-за ремонта муниципальных сетей в Риддере. Канал возвращён на основной маршрут.',
    acknowledged: true,
    acknowledgedAt: '11:45',
    acknowledgedBy: 'Автоматическая служба NOC',
    duration: '1 час 15 мин',
    timeDetected: '11:20:00',
    potentialReason: 'Переключение на резервный радиорелейный пролёт с повышенной задержкой',
    timeline: [
      { timestamp: '11:20:00', stage: 'Срабатывание', note: 'Пинг превысил 150 мс и составил 168 мс', level: 'warning' },
      { timestamp: '12:35:00', stage: 'Восстановление', note: 'Основная оптика восстановлена. Пинг нормализовался до 29 мс', level: 'normal' },
    ],
  },
];

export const INITIAL_EARLY_WARNINGS: EarlyWarning[] = [
  {
    id: 'EW-101',
    schoolId: 'SCH-014',
    schoolName: 'Катон-Карагайская сельская школа им. С. Рыкова',
    currentStatus: 'Warning trend',
    detectedPattern: 'Последовательный рост задержки: 72 → 84 → 96 → 109 → 121 мс (за последние 15 минут)',
    metricType: 'ping',
    currentValue: '121 мс',
    projectedValue: '155 мс (превышение порога 150 мс через ~12 минут при сохранении динамики)',
    projectedTime: '~12 минут',
    recommendedAction: 'Проверить очередь локального маршрутизатора; уведомить районного провайдера о перегрузке uplink-канала.',
    confidence: 'High',
    metricsTrend: [72, 84, 96, 109, 121],
    detectedAt: '6 минут назад',
  },
  {
    id: 'EW-102',
    schoolId: 'SCH-003',
    schoolName: 'Средняя профильная школа №25',
    currentStatus: 'Warning trend',
    detectedPattern: 'Плавное падение входящей скорости: 45 → 38 → 29.5 → 22 → 18.4 Мбит/с',
    metricType: 'download',
    currentValue: '18.4 Мбит/с',
    projectedValue: '11.0 Мбит/с (приближение к критическому порогу 5 Мбит/с)',
    projectedTime: '~25 минут',
    recommendedAction: 'Выявить фоновую синхронизацию тяжёлых файлов или запуск внепланового обновления учебных ПК.',
    confidence: 'Medium',
    metricsTrend: [45, 38, 29.5, 22, 18.4],
    detectedAt: '14 минут назад',
  },
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-001',
    timestamp: '14:26:08',
    schoolId: 'SCH-014',
    schoolName: 'Катон-Карагайская сельская школа им. С. Рыкова',
    type: 'early_warning',
    message: 'Сработало раннее предупреждение: Ping плавно увеличился до 121 мс (тренд: ухудшается)',
    severity: 'warning',
  },
  {
    id: 'act-002',
    timestamp: '14:25:30',
    schoolId: 'SCH-006',
    schoolName: 'Многопрофильный лицей №1 (г. Риддер)',
    type: 'incident_resolved',
    message: 'Инцидент INC-4078 решён: Основная оптика восстановлена, пинг в норме (29 мс)',
    severity: 'normal',
  },
  {
    id: 'act-003',
    timestamp: '14:24:12',
    schoolId: 'SCH-017',
    schoolName: 'Средняя школа посёлка Жезкент',
    type: 'incident_new',
    message: 'Новый активный инцидент INC-4091: Потери пакетов достигли 12.8% (порог: 10%)',
    severity: 'critical',
  },
  {
    id: 'act-004',
    timestamp: '14:23:45',
    schoolId: 'SCH-001',
    schoolName: 'Школа-гимназия №38 (г. Усть-Каменогорск)',
    type: 'health_improved',
    message: 'Состояние сети улучшилось до 95/100 после стабилизации пропускной способности',
    severity: 'normal',
  },
  {
    id: 'act-005',
    timestamp: '14:21:00',
    schoolId: 'SCH-020',
    schoolName: 'Урджарская гимназия №1 им. Абая',
    type: 'agent_offline',
    message: 'Предупреждение агента: Нет измерений в течение 14 минут (Агент офлайн)',
    severity: 'warning',
  },
  {
    id: 'act-006',
    timestamp: '14:18:22',
    schoolId: 'SCH-018',
    schoolName: 'Аксуатская средняя школа №1',
    type: 'incident_new',
    message: 'Новый активный инцидент INC-4092: Ping увеличился до 295 мс на радиоканале',
    severity: 'critical',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Открыт критический инцидент',
    message: 'SCH-017 (Жезкент) фиксирует потерю пакетов 12.8%.',
    timestamp: '4 мин назад',
    read: false,
    type: 'incident',
    incidentId: 'INC-4091',
    schoolId: 'SCH-017',
  },
  {
    id: 'notif-2',
    title: 'Раннее предупреждение',
    message: 'SCH-014 (Катон-Карагай) постепенная деградация связи: пинг растёт 72 → 121 мс.',
    timestamp: '8 мин назад',
    read: false,
    type: 'warning',
    schoolId: 'SCH-014',
  },
  {
    id: 'notif-3',
    title: 'Агент не отправляет данные',
    message: 'SCH-020 (Урджар) компьютер школьного агента перестал передавать телеметрию (>10 мин).',
    timestamp: '15 мин назад',
    read: false,
    type: 'agent',
    schoolId: 'SCH-020',
  },
  {
    id: 'notif-4',
    title: 'Инцидент успешно решён',
    message: 'SCH-006 (Риддер) оптический маршрут восстановлен; задержка нормализована до 29 мс.',
    timestamp: '1 час назад',
    read: true,
    type: 'incident',
    incidentId: 'INC-4078',
    schoolId: 'SCH-006',
  },
];
